# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Kristin L. Muench
tagline:          'Human Being'
description:      'Data Scientist. </p>Biologist. </p>Human Being. <p><a href="https://twitter.com/kristin_muench" target="_blank">@kristin_muench</a></p>'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
